apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: Template for building Dyncamic Admission WebHook
    tags: infrastructure
  name: uac-build
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
      name: uac-webhook
      namespace: ${NAMESPACE}
  spec:
      tags:
      - from:
            kind: DockerImage
            name: docker-registry.default.svc:5000/${NAMESPACE}/identity
        name: latest
        importPolicy:
            scheduled: true
- kind: "BuildConfig"
  apiVersion: "build.openshift.io/v1"
  metadata:
    name: uac-webhook
    namespace: ${NAMESPACE}
  spec:
    runPolicy: "Serial"
    source:
      git:
        uri: ${GIT_URL}
    strategy:
      sourceStrategy:
        from:
          kind: "ImageStreamTag"
          name: "golang-s2i:latest"
          namespace: "openshift"
    output:
      to:
        kind: "ImageStreamTag"
        name: "uac-webhook:${VERSION}"
parameters:
- description: Specify current namespace
  name: NAMESPACE
  value: "bnhp-system"
  required: true
- description: Specify service GIT url
  name: GIT_URL
  value: "https://github.com/Dimss/uac.git"
  required: true
- description: Specify version
  name: VERSION
  value: "0.1"
  required: true
