apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: Template for deploying Dyncamic Admission WebHook
    tags: infrastructure
  name: uac-webhook
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: uac-adwebhook
- apiVersion: authorization.openshift.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: ad-webhooks
  roleRef:
    name: cluster-admin
  subjects:
  - kind: ServiceAccount
    name: uac-adwebhook
    namespace: bnhp-system
- apiVersion: admissionregistration.k8s.io/v1beta1
  kind: ValidatingWebhookConfiguration
  metadata:
    name: uac
    labels:
      app: uac
  webhooks:
    - name: ${SERVICE_NAME}
      clientConfig:
        url: https://${SERVICE_NAME}:8080/
        caBundle: ${BASE64_CA_BUNDLE}
      rules:
        - operations: [ "CREATE"]
          apiGroups: ["*"]
          apiVersions: ["*"]
          resources: ["oauthaccesstokens"]
      failurePolicy: Ignore
- apiVersion: v1
  kind: Secret
  metadata:
    name: uacerts
  type: Opaque
  data:
    server.crt: ${BASE64_SERVER_CRT}
    server.key: ${BASE64_SERVER_KEY}
- apiVersion: v1
  kind: Secret
  metadata:
    name: uaconfig
  type: Opaque
  stringData:
    http_crt: /uac/certs/server.crt
    http_key: /uac/certs/server.key
    ad_host: ${AD_HOST}
    ad_port: ${AD_PORT}
    ad_basedn: ${AD_BASEDN}
    ad_binduser: ${AD_BINDUSER}
    ad_bindpass: ${AD_BINDPASS}
- apiVersion: v1
  kind: Service
  metadata:
    name: uac
  spec:
    selector:
      app: uac
    ports:
    - name: http
      port: 8080
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: uac
    labels:
      app: uac
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: uac
    template:
      metadata:
        labels:
          app: uac
      spec:
        serviceAccountName: uac-adwebhook
        containers:
        - name: uac
          image: ${IMAGE}
          env:
          - name: UAC_HTTP_CRT
            valueFrom:
              secretKeyRef:
                name: uaconfig
                key: http_crt
          - name: UAC_HTTP_KEY
            valueFrom:
              secretKeyRef:
                name: uaconfig
                key: http_key
          - name: UAC_AD_HOST
            valueFrom:
              secretKeyRef:
                name: uaconfig
                key: ad_host
          - name: UAC_AD_PORT
            valueFrom:
              secretKeyRef:
                name: uaconfig
                key: ad_port
          - name: UAC_AD_BASEDN
            valueFrom:
              secretKeyRef:
                name: uaconfig
                key: ad_basedn
          - name: UAC_AD_BINDUSER
            valueFrom:
              secretKeyRef:
                name: uaconfig
                key: ad_binduser
          - name: UAC_AD_BINDPASS
            valueFrom:
              secretKeyRef:
                name: uaconfig
                key: ad_bindpass
          volumeMounts:
          - name: certs-volume
            mountPath: /uac/certs
            readOnly: true
          ports:
          - containerPort: 8080
        volumes:
        - name: certs-volume
          secret:
            secretName: uacerts
parameters:
- description: Specify docker imge
  name: IMAGE
  value: "docker.io/dimssss/uac:0.6"
  required: true
- description: Specify service name
  name: SERVICE_NAME
  value: "uac.bnhp-system.svc.cluster.local"
  required: true
- description: Specify base64 encoded CA crt for the webhook configuration
  name: BASE64_CA_BUNDLE
  value: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNyRENDQVpRQ0NRQy9TZXFnVElqOWVqQU5CZ2txaGtpRzl3MEJBUXNGQURBWE1SVXdFd1lEVlFRRERBeGgKWkcxcGMzTnBiMjVmWTJFd0lCY05NVGt3TkRNd01EazBPVEkyV2hnUE1qRXhPVEEwTURZd09UUTVNalphTUJjeApGVEFUQmdOVkJBTU1ER0ZrYldsemMybHZibDlqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQU1ieHM3dkdGQmkza3VGWFpFZ0tMM0MvWWRXbjFXUDlqQ1NDUlpEWUpxaTZvSzhNM0xKb2p3QjIKMEV5ejZSbUkwcEIxdjUxQXBlSjk2eXdZdEZtZHdrR0NUalVmUzA5TDNxRE81clh1UHd4cXNxWXpTa3h1VUJLWgoycnVYc1dJS25Kclh0bkZBZ1I2Qmd1M3dNdVFLTExoY3dmY2NmOTFGSWo1SnBibEtOZG41UUxMYk5FRmVhRmlMCmtBdlZnNjBzL3BhbjhJc0RxQnNTbWwxUmJxVnFkS3lUeUR2NUdxMmxncEhNUXo2NDZ3bUFNWE95OFh6dFZwQ0gKUHVxSnRUbm9Bempha3BJaUJJRGF4SXBqT1BDSmtIbkhSMjFvblNmUFJ3M0VSeFZSNCsrbVltbTJqNnQvVFMwYQpBTURkQy9lQmJoc2VjKzhmVW91WGFqbzlYVW9Id2VNQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBCnE1RHZCSGxNd0xYQlJ1OGYvTXlDUVhENFJvbFoyQ3NCRjRBRHk2UUlwN2NuL29JZ296SnBKQSt4QXlBeFhVMCsKakdkalhUWGFTT25NVmV0eTh6d3hSMVdxdFJhTlVqbTlvNWVZWmNiaitzV2gxOUpwZVRFaTNyZXE4OG5kcjRudApLbnJuYXd2V0hRNWFvYVNraWFxUFZONitJTk5ML1RWeTFBczZoWjliUEw0dWdRS3pjcVM0SnhCTlVHQ3ZrdmZ5CkovdW9BcXFnYWhTZTJlTE5kSWFsYWFuKzB0Q2lXZGVCdXpMTHQ5akM1dVdBZUg2YXVTbFBkb050YzZoNTZ6b0sKeTc2dUhRa243WlUzL085ZitWZWM2RnNla1V5OE1BZWJ1U04vZG55cHBJQ3JFWi8vZDBIUzB2ZnNXUDVBM25oQQpNWEJCTDVWSmNKc0JjSHpDOXhNM1RBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  required: true
- description: Specify base64 server crt for the HTTP server
  name: BASE64_SERVER_CRT
  value: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBVENDQWVtZ0F3SUJBZ0lKQU5iWUEwUWdKdEEzTUEwR0NTcUdTSWIzRFFFQkJRVUFNQmN4RlRBVEJnTlYKQkFNTURHRmtiV2x6YzJsdmJsOWpZVEFnRncweE9UQTBNekF3T1RRNU1qZGFHQTh5TVRFNU1EUXdOakE1TkRreQpOMW93TERFcU1DZ0dBMVVFQXd3aGRXRmpMbUp1YUhBdGMzbHpkR1Z0TG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMVJIb1dkSUlKUFNIVi85bUpraHEKNUUxay83Sm9SMnZBMHBZNk5lNWtaRWhnNlVIVUZ5U2YrL0xFOUJNeXZ1N2dIanMrR2F0T3ExcitNdHZpTjBsSgprM3ZNRiszbnVNQ2RnQ2loYUU3UDBxZU40cXZSTjlqVFJUa1Q4NDhQMEExR2hEdzJQV204Z3YwTGlqa24reXBKCkNtU0p4bWpoMi9uc0lPMm9FWUVXTGFQVmptTDdFcVJET1BpTXVlZmVmQld1c1lzOXF1MnNHTjRhaWNzSXNoTWMKRG5LSUhqdHJuTDVXZmlJN0pneHhDS0xWV1NzWG81WS9kbU5zWWpZQ2llSE1OTXlYUlZSSVBPWVBFN1ZhNEVtbwpsSlE1UndWQXR4R2haRGhhaVBvam5yWFJyL0tqNHBmVmUrN1VLbk5KYUlZU3BJSVlpY3l1Tk9qUXgvcW1sZW5SCnp3SURBUUFCb3prd056QUpCZ05WSFJNRUFqQUFNQXNHQTFVZER3UUVBd0lGNERBZEJnTlZIU1VFRmpBVUJnZ3IKQmdFRkJRY0RBZ1lJS3dZQkJRVUhBd0V3RFFZSktvWklodmNOQVFFRkJRQURnZ0VCQUI2VnBiSzJqYzRMOC8yQQpESkJmWmhaSzRJR3pnZ2VWT2JVNVFCK2x4VHlSYWRybmxkNU1ZYnNLL0dCYisxVUl1T2UrdmJ0WThoR2xqWUxnClpXdTJzZENaOVZ1d2t1LzhvVVA3SHpxS3kvdUYxaUJzSW5nRVJDdUhLOWtnd3BrZmxCbmVRWFczZGZGMzYxUEgKeHJSVGovYjFaOS9SdWtpQm12Z1lZaHpqajhjSmpEbUt2WWprcjZ0cEtkb2xaMVZ5QkozMXZBYTVrRlkyWEY3Vwo1azRtdXFnYXkxd1RJczJldllhVWNlSk9BQmN1WWozbm1IS3ZtZEllSldJWlJkeUozS0c0T0lnR1NPMnE4dERzCjNYK2lOdTgxRGE0V0R6cXBnMlZiUW5DR1E0Qi9sNXhWdEN4NzE2VmRDN0dxdENpbnZyYzl6ZDFGblp4bWRQNUcKeXcybzJ1QT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  required: true
- description: Specify base64 service key for the HTTP server
  name: BASE64_SERVER_KEY
  value: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBMVJIb1dkSUlKUFNIVi85bUpraHE1RTFrLzdKb1IydkEwcFk2TmU1a1pFaGc2VUhVCkZ5U2YrL0xFOUJNeXZ1N2dIanMrR2F0T3ExcitNdHZpTjBsSmszdk1GKzNudU1DZGdDaWhhRTdQMHFlTjRxdlIKTjlqVFJUa1Q4NDhQMEExR2hEdzJQV204Z3YwTGlqa24reXBKQ21TSnhtamgyL25zSU8yb0VZRVdMYVBWam1MNwpFcVJET1BpTXVlZmVmQld1c1lzOXF1MnNHTjRhaWNzSXNoTWNEbktJSGp0cm5MNVdmaUk3Smd4eENLTFZXU3NYCm81WS9kbU5zWWpZQ2llSE1OTXlYUlZSSVBPWVBFN1ZhNEVtb2xKUTVSd1ZBdHhHaFpEaGFpUG9qbnJYUnIvS2oKNHBmVmUrN1VLbk5KYUlZU3BJSVlpY3l1Tk9qUXgvcW1sZW5SendJREFRQUJBb0lCQUh0Y2V1SkdNR0QxRXNkbwpINFJhdVVpbFpxeUVac3V6SDFqTmtiWlg1OWdINzlRZFFPYUZWZnRSZTZhMDF0U2xDUzEzcjJTOVFqY0QzOWtpClpiOE10NFNrVUc0cVY5Y243Z2lkZlpZZXkwUnpyanBtc0NOZGJqVE43emM4eFRMMy9MUGpDS1JWNjhjTEt2dEUKVEZtbkNkTHlrckpGVno4OVcvRlVwOUk2b3RTWTBFTHFpS3VhcWM1MGhIcndOcUFvaTFZRG0vNEppK3Q0SWEvQwpBYitrY2FZYllrZFB1dkxtRGZxWEdXb1N2WVBIVTh2VDk0U1AyZmtjM0NNTDdneUpSbGd5UW5sSHF5bGVLOStECldqUFJnNWFwL0w0cFh4L1JQZWNvWkROVFREQTJVWmgvRGphL0hjSzk4cTJoL0tWSFNzVm0rTm1CKytwMGRQdEQKQXMzc1NBRUNnWUVBNmdHQnRkenZLczRvQjZyd01CbzIyUjFHdE9HVmM5bnM2YnY0cjFFeDFLRlhnWmlyTW5BWApuZzFsaGdTWmR6U1FhNEgrQnNlWU55dWxGTXJiOGkxeGtnb2ZKbXVTbnBSQktjOHZxUHVrWmh0cG5KQ29GNFU0CmowVE5NNVpxQlNUblMzYnVaVkhnMEtLdzZxZmh0dXRvQ1N6RkR1K1pKeVVzcEg5NDhYQW5OazhDZ1lFQTZSaW4KakRMVEE3elFFWE1CRCtsTUthQjVGM3UvQndxZEhpOEJJbm00YVdtcjFmc05SRGl1UlZ6azhnRjM0K3pDYlNwbgo3ZUZrM1ArQzRZelRqWGhtMFBYK21hR2IyY3Y5QUEzMW9EL0lkSFBKRHNKT0VRR1hxMXBldHlSRzAwUVYzYmtYCjJJUEhjMkFaT2grYU1WY0o5VTI4RStoL3MrSlhGVHoweXpkNFRJRUNnWUE5WmwvT2hFWU5DVUxmb0M2ZHNJTXIKdk03TXIxUXpyYjdJSlpZL0NpTDFFOUNPSkt6bTh4cC9VaXlOV2ErYTQ2UHhVWTZCNE9WRHRLUUFMS3BCaFVNRAplcnhwckZnd1c5NHRSanZQTHhnWDRxRjNmMDFidm96MHFxemRHRjZCTXdtdGQydGVFbm5XeEpsL09NVzA1VmZLCjhJQlVSdkg4bjNoelFTOU95b3EvYVFLQmdRRGN1ZDcyc0s0SERRV09jSE9pQ0k1NW9KN3FNT0VjbnQxWFZyVmgKV3hmWW9ocjQvc2w2UDU0dXlwOTExeFFiZmZoQ2ZYUjYyd096RGpWMnRlOGlPTkJMc1pYTkR5N1EyQXlVdjZOSApndjZqMzN5VmdFT0NjUnFaUlhNSlE4M1pndENkN0FiN25SWUNXQTZyYm4rSmwxMHpyOCtZbm9KRzZkOENtbjFICjdoZjVnUUtCZ0NOd3pVMytuMjh4WloxL1FMVDJyU2ZVTUxCZ0g0ZXZWNU5jVU8rREpJZ0N2VkdSM1JzYXBHeEkKcGQxK3U1VVM2REZZWitOYlJ1VUZ0N0FGSENWNFhPT1lVWTFtdStBZ2lEeHVpdHlVcFhXNFpNQlNJQWJ2U2NTMwpvSW5ZMkhRSkhsbUxxK0pLSjVpN3RURDNKVFFPcHc5L2V3OHdZTnBqNFVtUFQweWFOWVdUCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  required: true
- description: Specify Active Directory host
  name: AD_HOST
  value: "34.74.100.136"
  required: true
- description: Specify Active Directory port
  name: AD_PORT
  value: "389"
  required: true
- description: Specify Active Directory base dn
  name: AD_BASEDN
  value: "dc=ad,dc=lab"
  required: true
- description: Specify Active Directory bind user
  name: AD_BINDUSER
  value: "admin"
  required: true
- description: Specify Active Directory bind pass
  name: AD_BINDPASS
  value: "!q2w3e4r"
  required: true
