apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: Template for deploying Dyncamic Admission WebHook
    tags: infrastructure
  name: uac-webhook
  namespace: openshift
objects:
- apiVersion: admissionregistration.k8s.io/v1beta1
  kind: ValidatingWebhookConfiguration
  metadata:
    name: uac
    labels:
      app: uac
  webhooks:
    - name: ${SERVICE_NAME}
      clientConfig:
        url: https://${SERVICE_NAME}:8080/
        caBundle: ${BASE64_CA_BUNDLE}
      rules:
        - operations: [ "CREATE"]
          apiGroups: ["*"]
          apiVersions: ["*"]
          resources: ["oauthaccesstokens"]
      failurePolicy: Ignore
- apiVersion: v1
  kind: Secret
  metadata:
    name: uacerts
  type: Opaque
  data:
    crt: ${BASE64_SERVER_CRT}
    key: ${BASE64_SERVER_KEY}
- apiVersion: v1
  kind: Secret
  metadata:
    name: uaconfig
  type: Opaque
  data:
    http_crt: /uac/server.crt
    http_key: /uac/server.key
    ad_host: ${AD_HOST}
    ad_port: ${AD_PORT}
    ad_basedn: ${AD_BASEDN}
    ad_binduser: ${AD_BINDUSER}
    ad_bindpass: ${AD_BINDPASS}
- apiVersion: v1
  kind: Service
  metadata:
    name: uac
  spec:
    selector:
      app: uac
    ports:
    - name: http
      port: 8080
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: uac
    labels:
      app: uac
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: uac
    template:
      metadata:
        labels:
          app: uac
      spec:
        containers:
        - name: uac
          image: ${DOCKER_IMAGE}
          env:
          - name: UAC_HTTP.CRT
            valueFrom:
              secretKeyRef:
                name: uaconfig
                key: http_crt
          - name: UAC_HTTP.KEY
            valueFrom:
              secretKeyRef:
                name: uaconfig
                key: http_key
          - name: UAC_AD.HOST
            valueFrom:
              secretKeyRef:
                name: uaconfig
                key: ad_host
          - name: UAC_AD.PORT
            valueFrom:
              secretKeyRef:
                name: uaconfig
                key: ad_port
          - name: UAC_AD.BASEDN
            valueFrom:
              secretKeyRef:
                name: uaconfig
                key: ad_basedn
          - name: UAC_AD.BINDUSER
            valueFrom:
              secretKeyRef:
                name: uaconfig
                key: ad_binduser
          - name: UAC_AD.BINDPASS
            valueFrom:
              secretKeyRef:
                name: uaconfig
                key: ad_bindpass
          volumeMounts:
          - name: certs-volume
            mountPath: /uac
            readOnly: true
          ports:
          - containerPort: 8080
        volumes:
        - name: certs-volume
          secret:
            secretName: uacerts
parameters:
- description: Specify docker imge
  name: DOCKER_IMAGE
  value: ""
  required: true
- description: Specify service name
  name: SERVICE_NAME
  value: "uac.bhnp-system.svc.cluster.local"
  required: true
- description: Specify base64 encoded CA crt for the webhook configuration
  name: BASE64_CA_BAUNDLE
  value: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNyRENDQVpRQ0NRQ0dndmRMU3B0dXlUQU5CZ2txaGtpRzl3MEJBUXNGQURBWE1SVXdFd1lEVlFRRERBeGgKWkcxcGMzTnBiMjVmWTJFd0lCY05NVGt3TkRNd01EY3hPRFU0V2hnUE1qRXhPVEEwTURZd056RTROVGhhTUJjeApGVEFUQmdOVkJBTU1ER0ZrYldsemMybHZibDlqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQU1CYTRXRHRhRGtuMGtGK1FwZnZaZnZrYk1tOU9MQ3RuS01hbzN6RksrQXBLUnpOZ2ZuMHNkMjQKQmxUOXBBK050YmRNbDc0MTU1eWpPOTNvMHZ6aUJwRU5xUmFqc0RGTUZ1YUlOdk1RbjdyVllkREN4ZFc1OWVDawovU0xEZ2hwMUtaRm54TmY4RUtsMDZlSDNnaTdpNmhBQml5dHowUDg3c1QybDA2M0N0TU9Kb01VRU4yVFdLcWpBCmJodUdkVVJLYXNPMndwaGhPb21WOGEyYlhNMEVoWHhiMnVoZlRPNDdvNlZjbmNQN29MRCtQOVlBTnhjelJhU0YKVzNiVVRQcWR3ZGRLUUlQVWxkb0VoYk00S2V3dDhocGV1WGdNUkFmMEtTM2hrMEJHbXVLckh4ZE5FMCt1azhmVApUSTN1b29vQi9sNjhDcWI2Rkd1MUwwNm9XMnFRNWFrQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBCmkrYitRRE9RMzlMT1NnM1B6aWJBSjVYT1VRcnUyaEQyM1JoZnU1TjFqbkxON3E4dFFjMVZMV0Jac0l6WFBDeXIKUGVrd0NLN3RLaTIzVG8zOUQ0bW56dmx3YUNlcFJoM2tNQjY2dVNIVUswc2swczFCZjNBQldFcXhjZURqeXZGdwpEdjB0V3dEVU1INTNlMWdMOEMvL0RJOXFNckFHNTB0T0pwZFN6a3B6SjIydW8yeS8zSUhidUtITkJUS1o4N0lJCnJ3Qzh0YkN6M1g0SmJrdGw5anAzK1U5YlRhWG9QVkptRjVmTE5rRzU5N3NHbENKbDVSOFk5cnhneGVmVTQzVHYKYitTaUVGeE0xVzdWakJKVzc2V1RPeExRczRCZnFacklGOEgyL2FXSm9Vd0REbDZYU1BPSUloN21XNWFEdWREYwpJWlpxdzQzNENYNEF0dEJLV0NmS3NBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  required: true
- description: Specify base64 server crt for the HTTP server
  name: BASE64_SERVER_CRT
  value: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBVENDQWVtZ0F3SUJBZ0lKQUp5M1JlT05TamRSTUEwR0NTcUdTSWIzRFFFQkJRVUFNQmN4RlRBVEJnTlYKQkFNTURHRmtiV2x6YzJsdmJsOWpZVEFnRncweE9UQTBNekF3TnpFNE5UbGFHQTh5TVRFNU1EUXdOakEzTVRnMQpPVm93TERFcU1DZ0dBMVVFQXd3aGRXRmpMbUpvYm5BdGMzbHpkR1Z0TG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdzVnamZaZVZpMUxIdmNPczM2dGUKZVdhc2pZTVBtU2VacWhKangwUnk2U1FLOWk4VmJTUUY4a3Fwd1l2U3RFNzdaSDNrcE4zaTYxQVkxK3Q3R2VYUgpuUTJ6T0dvcHRiYmdZRVJDckFqb1QzTVUwbnd0UGFVbktKOFJnTHdpdUVMY1RzTWRPWU1rcUt5eHZReHE2SVZaCnZ5YkV6ZFJpdWZGZEhPSFJGZXZmdzRmVEZMWDVnZVh4dTZKeWhneWRRWGJYVEliWFdaMHIrQllJajNway9FVlAKR3lkVFVFQSt1L05mZFVXVkdmZllhYW1RQXo0UStTbENuTWVPWVMwUlIxUEhHd1JIRUJXc0hDbC9rNE56TUd2NQprVTV1dmRCVUZpL2ZmVW5ZQW9QR1Y4ck1GRDBMU3hjblJrazhXQkRFVks1YTBNZ2ZTT25QRFo4c28wN2dsYXp6Cmd3SURBUUFCb3prd056QUpCZ05WSFJNRUFqQUFNQXNHQTFVZER3UUVBd0lGNERBZEJnTlZIU1VFRmpBVUJnZ3IKQmdFRkJRY0RBZ1lJS3dZQkJRVUhBd0V3RFFZSktvWklodmNOQVFFRkJRQURnZ0VCQUxWODdVVTl3bTU4TlFDMQpKS2lmZXdYL0ZEbkhOVm8xVWF1ZGxXbGRvZDUvNmU2V2MveE9vZ3JSMjluQzZrWUJMWUl3cm1UUlZoQVJyZzkrCndWZTNKV0RybWphUmxqUUY3NUJpby9GQVFmblpoWXN1U1k5RVpwQkhuVUxvTGNIaGF6bXZSeStHTHhsN2V1WVUKdFV2U3I1eS90N210eitaS2I5SDQxaE5XMTBaWmlJdU44dVJEZ3BVVVd4QmhPcmRqYjlUbi9YRmxQMHMvemNURwplMDFXaUVIVmNkQ2ppWGxFRXRJZGhpVGl0cm0wZEpwaWxsK2ZLZmRwa2o1WVZsVlFySnpUT0gyQUI2bklQeFRPCkxGS0Y4eWtQbWwyRzBhWDdyUzBwYzF6VTNEUndMNXBrL0VBN0hCcU9zY3o5SjBMVDVKMllNOHIxSTJlMkYzaG8KVFZyREpNND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  required: true
- description: Specify base64 service key for the HTTP server
  name: BASE64_SERVER_KEY
  value: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdzVnamZaZVZpMUxIdmNPczM2dGVlV2FzallNUG1TZVpxaEpqeDBSeTZTUUs5aThWCmJTUUY4a3Fwd1l2U3RFNzdaSDNrcE4zaTYxQVkxK3Q3R2VYUm5RMnpPR29wdGJiZ1lFUkNyQWpvVDNNVTBud3QKUGFVbktKOFJnTHdpdUVMY1RzTWRPWU1rcUt5eHZReHE2SVZadnliRXpkUml1ZkZkSE9IUkZldmZ3NGZURkxYNQpnZVh4dTZKeWhneWRRWGJYVEliWFdaMHIrQllJajNway9FVlBHeWRUVUVBK3UvTmZkVVdWR2ZmWWFhbVFBejRRCitTbENuTWVPWVMwUlIxUEhHd1JIRUJXc0hDbC9rNE56TUd2NWtVNXV2ZEJVRmkvZmZVbllBb1BHVjhyTUZEMEwKU3hjblJrazhXQkRFVks1YTBNZ2ZTT25QRFo4c28wN2dsYXp6Z3dJREFRQUJBb0lCQVFDVTNQck9BSXVob1J4QwpjbVhsU2RFNmhvbDNuck5GZGwwK2tvWjhSNzFKY2RRaDhFM1haaDVjZkxUY2lLV1I4N2Jqa2VsdURTNUN1QkJnCmJXbWdtVWhDeHdXTFAwbUZjcTBzdDJjaTloaVJOMTQyb0tueUMvdFVzRlFxN1lWalJnZlVyaTFVODFuNFFvOTMKK2JaNFI5MjVYVEZXRW5vZFdQVHNJWFgzd0REcTUrTTdBazN3cmhRSy90SmF4Zm10NXZ5TFNNSVJyc3Bjd0xzRwpsZnBodFgxcWtZQ05HYVg1bkMzTW1RSnlYZE9GYjB2a21XN25TYW5oYlFNaDVPWll4eEp0UVFVWDB0Nzdyc2RRCnFUbkN0bzU4Q24yZHhBeVIwUkk2MGk4a29OWlFodk5Ld1FvZkMzQWxXNHlmUFlkQnc0NHlMcG1qVXB3MlYzQ24KNy9WZ1Nhb1pBb0dCQVBzd1BkZFU1Vmc3R3JDV1Y4bVJGNW1jVFAyUytzSXEvdnp2dkYxM2hINU1OL3U3bkU0ZwpzTVJGMTVXdnFkdldLUGZ0VWtGZlJKVW8zM3V3U2FTMHRQNFNoc1pDSndaekw2MEo2L2hOOHU3Ylg3Z3BTbjFYCjdYSzQ2T3pvbGtXRXNpY3VLampXNG5xa1VQempmTy9aNDRaeWRod3JseHpucWZzUVgxVFNCZzhOQW9HQkFNZFgKUjEyUmVDa29lL3kwWTZmRmZtQ0g3MWR1UW85YUxnWStYQmU2ZGFGVCtRcXhvZVdUV2E5QkVoODlUVnNkTU5HMgpoZTRJWHUraWhsMUFDQXJ1R244QVg2UVVrZVVlbmdkeUFXYVhaT2ExZEkyWFloN2YremVwbWNLV1FCNjkvdHJLCmFIZXBOZVVYSWxsbW5kTk5obnM0T29SUmlLdTZWU3pRZEhRWTcralBBb0dCQUlMNU9JV2E0cXNLeG5QbE1Ja04KZW56Q0h2THBQSThaMURNVzNlVHVlTXRSK3E3cnVDaVVxeGJzUStqczIyaWhWbU5QLzEvT3lQZnRnL24raGFlNApBZGVvMlZWdkVPSXdGVi9vbUgyMFIwTjhaNENqSnhBTVZPZEl1MHNzUzQ2Y0RqaVh2YlE5ZDRIelE3ZFk5c0FwCm9KVnVBVi9XNnNoTGt6b3g0ME5hNzRYUkFvR0FjcFVKc1pBWG1OanJoQk9Rb1BSVnMxa1B5NXJXYVo0MWpHTTEKL25Hd2dkNUo3Y3F6TzhwYUovSG9YOHFWOTRTczlpN0xoMHFLZjRaVlk2NlZzT3F5a2tQOXRjd1pITEZmdHZuaQpNajFkdzN1VUZudG83RVJsRzliQ1NtYWhUc3A1ZnZ3UDFwQ09LVFFHQzR0L3R1RCtKei9uNnYwTzZWOCs3SGFhCktjM1h3V01DZ1lCbHVrdjJHN3pxdWMyUSt2R0RsZ3hTRndrWnBOUGV3MGt5TWdBLzNsT2lVMEdEL2RmOEd0WEUKSU1ybkVYWlJFb2x6bTdwZDk5bWJrejNCZS9zaERPSm56YnVXR3o3YVNTdWJFVEdMdXhCN1U1UENDWmg3eFNDdgpPMmxWaUhIT3UrMFpYTkFpTEpSbUlWc09iMGhBcDJpQnRud1BIQmFYSkNJNkx5YjNwK3pZalE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
  required: true
- description: Specify Active Directory host
  name: AD_HOST
  value: "34.74.100.136"
  required: true
- description: Specify Active Directory port
  name: AD_PORT
  value: "389"
  required: true
- description: Specify Active Directory base dn
  name: AD_BASEDN
  value: "dc=ad,dc=lab"
  required: true
- description: Specify Active Directory bind user
  name: AD_BINDUSER
  value: "admin"
  required: true
- description: Specify Active Directory bind pass
  name: AD_BINDPASS
  value: "!q2w3e4r"
  required: true
