apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: 172.20.10.5
  labels:
    app: 172.20.10.5
webhooks:
  - name: 172.20.10.5
    clientConfig:
      url: https://172.20.10.5:8080/
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNyRENDQVpRQ0NRRDBkTUNpb1U5dld6QU5CZ2txaGtpRzl3MEJBUXNGQURBWE1SVXdFd1lEVlFRRERBeGgKWkcxcGMzTnBiMjVmWTJFd0lCY05NVGt3TXpJMk1UQXlNVEF5V2hnUE1qSTVNekF4TURneE1ESXhNREphTUJjeApGVEFUQmdOVkJBTU1ER0ZrYldsemMybHZibDlqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQUw2K2tNZUpEQUp0R3RjMWUrN3dZa0QyUU1vWkYrY1lEMUZhSDlvVzM0YU9lR3lqWmxNMW8yUkIKcEttTXlKQkNNc3h1Qk9CbXVRTzY1MFhmM09CN0YzamdXQ01CWTZncHZYeHdCUXcyZEN5WlV6OWlmaGdxMHpNQwpwWEdQQ3VseFRrM1BZTWFwTUhPVHNaRG54WnRBR3ZGRW5oU1BoMlY4UVNaN1dncDU1aUZZZXUrZlEvNHF6dmlJClE3SjF1VTd6TkNkTm15eSt1Tk52bEJJL3dlbVVBMDlKL21xbG9MTWZvaEZhb3dDOW93eEQ1V093QUI1ZEtDWmYKbVJjTVBBTEgxVWhQY21uNzdZYy94YVQ1SkZjZVRhOElFaERudk9XMUZVWUo3dU5ROGltN3Ryd3RQOWdOZEkrcwpCWG40L0Eza1JMMkVxeHl6b0l1VmwraW03cFd3Q2NVQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBCkJqUkxRR2VTTGU2Qkw4dlRIL09EbVhEYWZVcmpoc3Z4eXdkdUo0NHBLeCtTQ2NUQ0E4ekpEOEQ3NEFRY0JGME4KL2hzbmlMcEI2aUxwOVd1aHhhWGZ5cDAzeS85WWhGSjRjZHlYbVBoUVVYeFJJVXdSRFo0K0lMQlkrSU1ESUFERQpMdENxWjJkMHppbUcwRHdURy92dUlCWG9QVCtjNktTQmV2WFFVM09vQStVNWRMRC9ObjhQOW9XRmNROUpGV013CnFoUkl1RW1IOXowY2toNjYzRnBiWjVoNUhqQWRnQURTOVM5ZW9kcVBRTGhyTlc4WnZOeTNLSWdzTHFVdnV5cE8KM0J3ZlZNWHVuaENIRHYyR2Z2Um93QWhpSmRWeWYvZXpoZnBxWitwRldjZXVPd2FUbDhGbkRmWlFSSDVoVXhhZgprQllNMURKQWFNSGswRWdNYi9UT0lRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
    rules:
      - operations: [ "CREATE", "UPDATE", "DELETE", "CONNECT" ]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["oauthaccesstokens"]
    failurePolicy: Ignore
